// <auto-generated>
//  Maps Wwise event names onto the original .wav sources recovered from
//  Meniscus_WwiseProject. Generated for the WebGL build, where the native
//  Wwise sound engine is unavailable.
//
//  Sources, in order of authority:
//    bank   - GeneratedSoundBanks/Mac/Event/*.json (what Wwise actually played)
//    xml    - Wwise work-unit XML (event -> action -> target -> source)
//    family - numbered variation set of an event resolved by name
//    named  - resolved by name against the Originals pool
// </auto-generated>

using System.Collections.Generic;

namespace Meniscus.WwiseShim
{
	public static class WwiseAudioMap
	{
		public readonly struct Entry
		{
			public readonly string[] Clips;
			public readonly bool Loop;
			public readonly string Stops;

			public Entry(string[] clips, bool loop, string stops)
			{
				Clips = clips;
				Loop = loop;
				Stops = stops;
			}
		}

		public const string ResourcePath = "WwiseAudio/";

		public static readonly Dictionary<string, Entry> Events = new Dictionary<string, Entry>
		{
			{ "Play_24Bit_Piano_Chords_Melodie_State2_3_102BPM", new Entry(new[] { "24Bit_Piano_Chords_Melodie_State2-3_102BPM" }, true, null) },
			{ "Play_Bandana_03", new Entry(new[] { "Bandana_03" }, false, null) },
			{ "Play_Cat_Miau", new Entry(new[] { "Cat_Miau" }, false, null) },
			{ "Play_Cat_purring_yawning", new Entry(new[] { "Cat_purring_yawning" }, true, null) },
			{ "Play_Cat_slurping", new Entry(new[] { "Cat_slurping" }, false, null) },
			{ "Play_Fee_brummen_01", new Entry(new[] { "Fee_brummen_01" }, false, null) },
			{ "Play_Klick_02", new Entry(new[] { "Klick_02" }, false, null) },
			{ "Play_Lose", new Entry(new[] { "Piano_Ende_Langsam" }, false, null) },
			{ "Play_Piano_Auftakt", new Entry(new[] { "Piano_Auftakt_State1_82BPM" }, true, null) },
			{ "Play_Piano_Chords_State1_82BPM", new Entry(new[] { "Piano_Chords_State1_82BPM" }, true, null) },
			{ "Play_Whistle_02", new Entry(new[] { "Whistle_02" }, false, null) },
			{ "Play_bar_ambience01", new Entry(new[] { "bar_ambience01" }, true, null) },
			{ "Play_buying_01", new Entry(new[] { "coins_on_wood09" }, false, null) },
			{ "Play_coin_on_wood", new Entry(new[] { "coin_on_wood01", "coin_on_wood02", "coin_on_wood03" }, false, null) },
			{ "Play_coindrop01_into_water", new Entry(new[] { "coindrop01_into_water", "coindrop02_into_water", "coindrop03_into_water", "coindrop04_into_water", "coindrop05_into_water", "coindrop06_into_water", "coindrop07_into_water", "coindrop08_into_water" }, false, null) },
			{ "Play_coinflip", new Entry(new[] { "coinflip02", "coinflip03", "coinflip05", "coinflip06" }, false, null) },
			{ "Play_coins_on_wood", new Entry(new[] { "coin_on_wood01", "coin_on_wood02", "coin_on_wood03" }, false, null) },
			{ "Play_dogBite02", new Entry(new[] { "dogBite02" }, false, null) },
			{ "Play_exhale", new Entry(new[] { "exhale" }, false, null) },
			{ "Play_gibberish_04", new Entry(new[] { "gibberish_04" }, true, null) },
			{ "Play_lighter", new Entry(new[] { "lighter" }, false, null) },
			{ "Play_music", new Entry(new[] { "Piano_Chords_State2_102BPM" }, true, null) },
			{ "Play_pageclose", new Entry(new[] { "pageclose" }, false, null) },
			{ "Play_pageflip", new Entry(new[] { "pageflip" }, false, null) },
			{ "Play_something", new Entry(new[] { "something" }, false, null) },
			{ "Play_spill", new Entry(new[] { "waterspill01", "waterspill02", "waterspill03", "waterspill04" }, false, null) },
			{ "Play_tschickpack", new Entry(new[] { "cigarettepack" }, false, null) },
			{ "Play_wakingup", new Entry(new[] { "wakingup" }, false, null) },
			{ "Play_waterspills", new Entry(new[] { "waterspill01", "waterspill02", "waterspill03", "waterspill04" }, false, null) },
			{ "Play_zoom", new Entry(new[] { "zoom" }, false, null) },
			{ "Stop_Cat_purring_yawning", new Entry(null, false, "Play_Cat_purring_yawning") },
			{ "Stop_gibberish_04", new Entry(null, false, "Play_gibberish_04") },
		};
	}
}
